2020-06-24 18:39:39,437 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 276, in view_db
    return render_template('view_db.html', keyed_attrs=keyed_attrs)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/view_db.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/base.html", line 45, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/view_db.html", line 12, in block "content"
    <td><a href=" {{ url_for('edit') }} ">Edit</a></td>
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit'. Did you mean 'edit_profile' instead?
2020-06-24 18:45:17,865 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-24 18:45:19,081 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 276, in view_db
    return render_template('view_db.html', keyed_attrs=keyed_attrs)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/view_db.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/base.html", line 45, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/view_db.html", line 12, in block "content"
    <!--        <td><a href=" {{ url_for('edit') }} ">Edit</a></td>-->
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit'. Did you mean 'edit_profile' instead?
2020-06-24 18:46:25,000 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
