2020-06-23 10:27:22,282 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 264, in view_db
    print(c, ck, user[ck])
TypeError: 'User' object is not subscriptable
2020-06-23 10:27:36,165 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:29:35,044 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:29:37,141 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 264, in view_db
    print(c, ck, user.get(ck))
AttributeError: 'User' object has no attribute 'get'
2020-06-23 10:29:51,539 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:29:52,892 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 264, in view_db
    print(c, ck, user.getattr(ck))
AttributeError: 'User' object has no attribute 'getattr'
2020-06-23 10:29:54,520 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 264, in view_db
    print(c, ck, user.getattr(ck))
AttributeError: 'User' object has no attribute 'getattr'
2020-06-23 10:30:29,305 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:30:53,709 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:30:56,333 ERROR: Exception on /view_db [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 264, in view_db
    print(c, ck, user.getattribute(ck))
AttributeError: 'User' object has no attribute 'getattribute'
2020-06-23 10:33:57,872 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:35:00,011 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:37:34,782 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:48:24,485 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:54:31,057 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:59:00,988 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 10:59:51,167 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 11:04:32,527 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-23 11:05:22,149 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-24 18:39:26,747 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
