2020-06-22 12:32:17,393 ERROR: Exception on / [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 45, in index
    return render_template('index.html', title='Bonanzaz', form=form, posts=posts)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/base.html", line 45, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/index.html", line 20, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-06-22 12:32:21,154 ERROR: Exception on /index [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 45, in index
    return render_template('index.html', title='Bonanzaz', form=form, posts=posts)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/base.html", line 45, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/ilja/Dropbox/flask-megatut/app/templates/index.html", line 20, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-06-22 12:33:27,013 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:72]
2020-06-22 12:52:33,403 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:72]
2020-06-22 12:57:50,903 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:72]
2020-06-22 13:07:20,953 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-22 13:58:08,980 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-22 13:58:16,490 ERROR: Exception on /reset_password_request [GET] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 225, in reset_password_request
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
2020-06-22 14:00:59,597 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
2020-06-22 14:01:26,483 ERROR: Exception on /reset_password_request [POST] [in /Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ilja/.virtualenvs/flask-megatut-FibpGiLO/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ilja/Dropbox/flask-megatut/app/routes.py", line 233, in reset_password_request
    send_password_reset_email(user)
  File "/Users/ilja/Dropbox/flask-megatut/app/email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "/Users/ilja/Dropbox/flask-megatut/app/email.py", line 10, in send_email
    msg = Message(subject, sender=sender, recipients=recipients)
TypeError: __init__() got an unexpected keyword argument 'sender'
2020-06-22 14:02:45,826 INFO: Microblog startup [in /Users/ilja/Dropbox/flask-megatut/app/__init__.py:76]
